#!/bin/bash
myIP=`curl -q ifconfig.me 2> /dev/null`
siteIP=`dig +short zbychuk.sly.io`

echo "$myIP
$siteIP"

if [ "$myIP" == "$siteIP" ]
then internet="no"
else internet="yes"
fi

usage()
{
    echo "
Jak używać: ipxe [ -d ] [ -u ] [ -c ... ] | [ -h ]

 -d ściągnij źródła
 -u załaduj na serwer omv1
 -c kompiluj - jaki iPXE budować
     zbychuk: buduję go dla mojej domowej sieci LAN (autor).
    internet: iPXE dla konfiguracji z poza sieci -zbychuk-.

 -h wyświetlenie tej instrukcji
"
}

if [ "$#" = 0 ]; then
    usage
    exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
        -d )          download="yes"
                                ;;
        -u )          upload="yes"
                                ;;
        -c )          shift
                      net=$1
                      compile="yes"
                                ;;
        -v )          verbose="yes"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 0
    esac
    shift
done

cd
mkdir -p ipxe
mkdir -p ipxe-image

if [ "$download" = "yes" ]; then
    rm -rf ipxe
    mkdir -p ipxe
    wget -c https://github.com/ipxe/ipxe/archive/master.zip -O ipxe-master.zip
    unzip ipxe-master.zip
    rm ipxe-master.zip
    mv ipxe-master/* ipxe
    rm -rf ipxe-master

    #git clone git://git.ipxe.org/ipxe.git
fi

if [ "$compile" = "yes" ]; then
    case $net in
        zbychuk )      serwer="omv1:82"
                       echo "#!ipxe
dhcp
chain --replace --autofree http://omv1:82/ipxe/setup.php
" > ~/ipxe/src/embeded.ipxe
                       serwer="omv1:90"
                       ipxe_config="http://$serwer/ipxe/general.h"
                                ;;
        internet )     serwer="omv1:90"
                           if [ "$internet" = "yes" ]; then
                               serwer="zbychuk.sly.io:90"
                           fi
                       ipxe_config="http://$serwer/ipxe/general.h"
                       menu="http://$serwer/ipxe/inet.ipxe"
                       curl -sSL $menu -o ~/ipxe/src/embeded.ipxe
                                ;;
        * )            echo
                       echo "Nie podałeś parametru -c [ zbychuk | internet ]"
                       echo
                       exit 0
    esac

    mkdir -p ~/ipxe-image/$net
    cd ~/ipxe/src
    curl -sSL $ipxe_config -o ~/ipxe/src/config/general.h
    make clean
    make bin/ipxe.iso EMBED=embeded.ipxe
    make bin/ipxe.usb EMBED=embeded.ipxe
    cp bin/ipxe.lkrn bin/ipxe.usb bin/ipxe.iso ~/ipxe-image/$net
    cp ~/ipxe/src/config/general.h ~/ipxe-image/$net/
    cp embeded.ipxe ~/ipxe-image/$net/
    cp $0 ~/ipxe-image/$net/
fi

if [ "$upload" = "yes" ]; then
    scp -r $HOME/ipxe-image/$net zbychuk@omv1:/sharedfolders/sysimages/ipxe/
    if [ "$net" = "zbychuk" ]; then
    scp -r $HOME/ipxe-image/$net/ipxe.lkrn zbychuk@omv1:/sharedfolders/tftp/ipxe/
    fi
fi

if [ "$verbose" = "yes" ]; then
    echo "compile:     $compile
internet:    $internet
net:         $net
menu:        $menu
ipxe_config: $ipxe_config
"
fi
