#!/bin/bash

apt update
apt upgrade -y
apt install -y mc gawk python aptitude links wget curl build-essential genisoimage \
 libncurses5-dev zlib1g-dev isolinux git gettext libssl-dev xsltproc liblzma-dev \
 dnsutils

myIP=`curl -q ifconfig.me 2> /dev/null`
siteIP=`dig +short zbychuk.sly.io`

echo "$myIP
$siteIP"

if [ "$myIP" == "$siteIP" ]
then
    server="omv1:90"
else
    server="zbychuk.sly.io:90"
fi

cd /usr/local/bin 
wget http://$server/openwrt/wrt
wget http://$server/ipxe/ipxe
chmod +x *

cd /
wget http://$server:90/docker-wrt/.config/mc.tar.gz
mkdir -p /root/.config
cd /root/.config
tar xvfz /mc.tar.gz
rm /mc.tar.gz
