#!/bin/bash

apt update
apt upgrade -y
apt install -y mc gawk python aptitude links wget curl build-essential genisoimage \
 libncurses5-dev zlib1g-dev isolinux git gettext libssl-dev xsltproc liblzma-dev \
 dnsutils

server="https://0to2.github.io"

cd /usr/local/bin 
wget $server/openwrt/wrt
wget $server/ipxe/ipxe
chmod +x *

cd /
wget $server/docker-wrt/.config/mc.tar.gz
mkdir -p /root/.config
cd /root/.config
tar xvfz /mc.tar.gz
rm /mc.tar.gz
